apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: group-sync-operator
  namespace: grpsyncoperator
spec:
  channel: alpha 
  name: group-sync-operator	
  source: community-operators 
  sourceNamespace: openshift-marketplace
